name: Label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  required:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "breaking, enhancement, bug, documentation, internal, skip changelog"
